/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'lisztian' at '6/30/17 3:12 PM' with Gradle 3.0
 *
 * @author lisztian, @date 6/30/17 3:12 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
